version: '3.1'
services:
  postgresql:
    image: postgres:12.0-alpine
    ports:
       - '9999:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
