version: '3.1'
services:
  postgresql:
    image: postgres:12.0-alpine
    ports:
       - '5432:5432'
    volumes:
      - ./motol/IdeaProjects/unit7
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password